---
# tasks file for apache
- name: Install Java
  package: name=java-1.8.0-openjdk state=installed

- name: Download Tomcat
  get_url:
    url: http://apache.cp.if.ua/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    mode: 0664

- name: Extract archive
  command: chdir=/usr/share /bin/tar xzf /opt/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{ tomcat_version }}
